version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - jupyter-book config sphinx docs/

sphinx:
  configuration: docs/_build/html/_generated/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

formats:
  - pdf
  - epub
